### ISSUE TITLE
CocoaPods

### ISSUE THREAD

**Issue by lfarah** [valdirunars/Lorikeet#1]
I'd be cool to also add Cocoapods support. I done this implementation myself last week for my library. Just follow [this post](https://guides.cocoapods.org/making/making-a-cocoapod.html) and [this checklist](https://github.com/thellimist/EZPods).

**Comment by valdirunars** [comment]
Absolutely. :) 

It’s next up on my wishlist
And thanks for the tip

**Comment by valdirunars** [comment]
I've been working a lot lately but I finally managed to find the time to do this

closing this issue now :)

**Comment by lfarah** [comment]
Thanks for taking time to add it! 🎉
